### Comprobar contraseña comprometida
POST http://localhost:8000/validate/
Content-Type: application/json
Accept: application/json

{
  "password": "sesamo",
  "mode": "generador"
}



### Ver status de la api
GET http://localhost:8000/health/
Accept: application/json